### ISSUE TITLE
Lacking constness

### ISSUE THREAD

**Issue by odraencoded** [Jebbs/DSFML#121]
Hey, today I noticed that [`Image.getPixel(x, y)`](https://github.com/Jebbs/DSFML/blob/master/src/dsfml/graphics/image.d#L208) is not a `const` method, even though it's marked as such in the [SFML documentation](http://www.sfml-dev.org/documentation/2.0/classsf_1_1Image.php#a8c8460e311dcb00557cb00a81c29163d).

That means you can't do this for example:

```
bool isRed(in Image image, in Vector2u p) {
    return image.getPixel(p.x, p.y) == Color.Red;
}
```

**Comment by KoczurekK** [comment]
Doesn't seem like we have a similar notion of 'tomorrow'. ;-)

Jokes aside, I should be able to handle this, are you ok with me sending a PR that adds `const` where necessary?

**Comment by Jebbs** [comment]
Everyone knows that software engineers can't do time estimates.

I'm always OK with PR's, so feel free!

**Comment by KoczurekK** [comment]
[Relevant PR](https://github.com/Jebbs/DSFML/pull/278)
