### ISSUE TITLE
Font.loadFromFile errors when file is missing instead of returning false

### ISSUE THREAD

**Issue by odraencoded** [Jebbs/DSFML#122]
Hey, it's me again. I'm not sure this is what should happens so I'm posting here. The code:

```
Font myFont = new Font();
assert(myFont.loadFromFile("arial.ttf"));
```

Executed in a directory without an `arial.ttf` file causes an error instead of `loadFromFile` returning false, which I thought is what was supposed to happen if it can't find/load the file.

Log:

```
object.Error: Access Violation
----------------
0x6C6418AD in sfFont_createFromFile
0x0043A553 in _Dmain at d:\Codings\MazeGame\source\main.d(11)
0x0044F6F4 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(ch
ar[][])*).runAll().void __lambda1()
0x0044F6C7 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(ch
ar[][])*).runAll()
0x0044F5E0 in _d_run_main
0x0043A594 in main
0x00476759 in mainCRTStartup
0x7636EE1C in BaseThreadInitThunk
0x776137EB in RtlInitializeExceptionChain
0x776137BE in RtlInitializeExceptionChain
Destroying Shader
Destroying Texture
Destroying Font
```

**Comment by sigod** [comment]
> Did MINGW introduce new dependencies with GCC 4.8? It seems I'm missing `libwinpthread-1.dll` (pthread library) which I wasn't missing before.

I just ran into the same issue. Can't start program without `libwinpthread-1.dll` in the same folder.
