### ISSUE TITLE
Antialias doesn't appear to work.

### ISSUE THREAD

**Issue by MatthewFrench** [Jebbs/DSFML#153]
I set anti alias to level 8, I verify that it is level 8 after window creation but my circles still look like poop.

**Comment by Jebbs** [comment]
I'll see if there is any difference for me, but it might just be something about the way a circle is drawn? 

If you're verifying that you get level 8, then you have level 8.

**Comment by MatthewFrench** [comment]
I followed the SFML 2.0 tutorial on circles and antialiasing. My circle looks a lot uglier than the example on the site.

**Comment by Jebbs** [comment]
What OS are you on?

**Comment by GanMatt** [comment]
Mac Os 10.10.2, Macbook Pro 2011

**Comment by GanMatt** [comment]
I was able to fix my issue by creating the circle at 10* the normal size and scaling down. Though I suppose it's just a temporary fix.

**Comment by Jebbs** [comment]
I'm at school right now, but I'll be able to look into this once I get home in a couple of hours. Unfortunately my OSX box is terrible so it is a little hard for me to do real testing for this, but I'll do my best. You shouldn't need to have a work around for something so trivial.

**Comment by luke5542** [comment]
I've wanted to use AA in my project, but only just got around to testing it and I see it on both OSX and Linux Mint 16 with the same level of 8. I have not tested my project under windows so can't say anything there.

**Comment by Jebbs** [comment]
@GanMatt / @MatthewFrench

Does the same issue happen when you use SFML?

**Comment by MatthewFrench** [comment]
I can't get SFML to run in Xcode. When I create a project from the SFML template, I get:
clang: error: unknown argument: '-frameworksfml-system'
clang: error: unknown argument: '-frameworksfml-window'
clang: error: unknown argument: '-frameworksfml-graphics'
clang: error: unknown argument: '-frameworksfml-audio'
clang: error: unknown argument: '-frameworksfml-network'

**Comment by Jebbs** [comment]
Are you able to compile via the command line?

Also, looks like my computer is worse than I thought and doesn't even support AA. Go figure. If @luke5542 is able to see it on his OSX system then it sounds like it's something specific to your computer so I am not sure what I can do to help.

**Comment by Jebbs** [comment]
So there might be more to this, I am not sure yet. 

Check this guy out: #154

**Comment by luke5542** [comment]
I've made a test in both SFML and DSFML on OS X showing what I get as a difference between having AA level 8 and AA level 0. This was run under OS X Yosemite 10.10.1 on a 2013 Mac Air.

I hope this helps. As you can see, DSFML is behaving identically to SFML, for me, and correctly setting the AA level.

![Anti-aliasing level 8](https://cloud.githubusercontent.com/assets/2971601/5939316/7fd3aa84-a6fa-11e4-9f16-b7e19a68d751.png)

![Anti-aliasing level 0](https://cloud.githubusercontent.com/assets/2971601/5939320/8933da04-a6fa-11e4-8720-3096f274f3ac.png)

**Comment by Jebbs** [comment]
Are either of you using the build I uploaded or are you building yourselves?

**Comment by luke5542** [comment]
I am using the build that you uploaded and linked in the README. The one dated "August 2nd, 2014".

**Comment by Jebbs** [comment]
@GanMatt / @MatthewFrench

Did you ever figure out what was going on?

**Comment by Jebbs** [comment]
Just another check in.

@GanMatt / @MatthewFrench 

Any changes to this?

**Comment by Jebbs** [comment]
@GanMatt / @MatthewFrench 

Unless you guys have any other news on this I'll probably close it in the next couple of days.
