### ISSUE TITLE
Drawing on OSX is broken...maybe?

### ISSUE THREAD

**Issue by Jebbs** [Jebbs/DSFML#154]
Looks like I need to spend more time with the OSX stuff. I haven't gotten any reports from anyone using it, so maybe it is just my old crappy system that it happens on, but basically drawing is broked. This is the issue I am experiencing:
![God. Damn it.](http://i.imgur.com/TKRDFQE.png)

**Comment by luke5542** [comment]
This is interesting... I haven't seen anything like this issue in my development on OS X. And I've made a similar test that also doesn't show this. I'm running on OS X Yosemite 10.10.1

![screenshot 2015-01-28 13 55 41](https://cloud.githubusercontent.com/assets/2971601/5939244/0e5205e0-a6fa-11e4-9d55-8af8778eea0d.png)

**Comment by Jebbs** [comment]
Yeah, the fact that it has only happened to me so far is a bit strange. I'm going to try profiling/debugging things later to see what it going on.

**Comment by Jebbs** [comment]
Haven't found anything that jumps out at me yet, though I have found out that this only seems to be the case for Shapes. I can draw a Sprite with a texture just fine.  Probably something strange going on with a Shape's vertex array.

**Comment by aubade** [comment]
Could there be a struct byte-alignment issue?

**Comment by Jebbs** [comment]
I find that hard to believe since drawing Sprites works, but I suppose it is possible. I'll do more investigation tomorrow. 

It takes me forever to do anything on OS X though.

**Comment by Jebbs** [comment]
Found out what happened.
After fixing this I'm surprised that this hasn't come up sooner.

This is the line in question: https://github.com/Jebbs/DSFML/blob/master/src/dsfml/graphics/shape.d#L88

Floats initialize to nan, and it was never set to anything. The outline of the shape was freaking out.

**Comment by SyntaxColoring** [comment]
:+1: Good catch.  Do you think this is happening anywhere else?

**Comment by Jebbs** [comment]
I hope not!
