### ISSUE TITLE
Full Port?

### ISSUE THREAD

**Issue by Jebbs** [Jebbs/DSFML#156]
This is mostly for fun!

I think it would be neat to try to port all of SFML to D and not just have it as a binding.

**Comment by luke5542** [comment]
This sounds interesting, and would definitely be awesome to see, if at least from the D perspective.

**Comment by SyntaxColoring** [comment]
I'm extremely interested in this.  If you'd like, I could get to work on it right away.  I was thinking about doing my own SFML rewrite from scratch, but it might be smarter to migrate code more gradually.

**Comment by Jebbs** [comment]
Sure, if you'd like. I don't know if this is the direction for the future, though. I mainly wanted to play around with this for academic reasons.

**Comment by Jebbs** [comment]
I'm closing this as I hardly have enough time to work on DSFML as is, let alone a full port.
