### ISSUE TITLE
Random Unicode Added in File Name

### ISSUE THREAD

**Issue by luke5542** [Jebbs/DSFML#162]
When trying to use `image.saveToFile(fileName);` I occasionally get some random extra unicode characters at the end of the file name, which throws off the file saving.

For example, I'm printing out, in my code, the string:

` ./20150221T143946/19-perlin.png`

and then getting an error of:

`Failed to save image "./20150221T143946/19-perlin.png▼ÇδH"`

I am using just the standard `string` in my code, and haven't yet tried to switch over to `dstring` or something, but either way this shouldn't be behaving like this. Any suggestions?

**Comment by FireEater64** [comment]
Could you try terminating your fileName with `\0`? I wasn't able to reproduce this, but looking at the handle for [saveToFile](https://github.com/Jebbs/DSFML/blob/9bd4f197cda544a2ae994379a6c7c2505402883d/src/dsfml/graphics/image.d#L326), it looks like a string terminator isn't appended before passing the pointer to SFML.

**Comment by Jebbs** [comment]
Oh, interesting. @FireEater64 is probably right about this. Really, I wonder how I missed this one.

**Comment by luke5542** [comment]
I've done exactly as he suggests and it has fixed my problem completely. I've also come up with a short test that includes the bug showing up every time:

```D
import std.stdio;
import dsfml.graphics;

void main()
{
	auto fileName = "fileNameTest.png";
	writeln("Save file: ", fileName, "__");

	auto len = fileName.length;
	fileName.length = 100;
	fileName.length = len;

	auto image = new Image();
	if(image.create(128, 128, Color.Black))
	{
		image.saveToFile(fileName);
	}
	else
	{
		writeln("Image creation failed");
	}
}
```

Which outputs, for me:

```
Save file: fileNameTest.png__
Failed to save image "fileNameTest.png
  "
```

I suggest passing in the string's length to DSFMLC when you save files. That may or may not be the best solution, but it should work.

**Comment by Jebbs** [comment]
There is a function I normally use (toStringz), but I guess I just forgot to use it here. Weird. It's an easy fix so I can pop it out today.

**Comment by luke5542** [comment]
Ahh, that's fair enough. Glad it's a simple fix, then.
