### ISSUE TITLE
How to get text from text entered event

### ISSUE THREAD

**Issue by kingsleyh** [Jebbs/DSFML#164]
In SFML you can get the text that was entered:
if(event.type == sf::Event::TextEntered)
    {
        userInput += event.text.unicode;
    }

How can I do this with DSML?

**Comment by kingsleyh** [comment]
nevermind figured it out - its the same :)

**Comment by aubade** [comment]
Yeah, apart from the use of properties and the differences in constructors, the API is pretty much identical. I learned the library using the vanilla SFML reference docs back before Jebbs put dsfml.com together.
