### ISSUE TITLE
graphics/vertexarray.d - PrimitiveType primativeType

### ISSUE THREAD

**Issue by MoodleLadyCow** [Jebbs/DSFML#165]
I was having some trouble setting the PrimitiveType for a VertexArray in my new project and with a little investigation, the trouble reavealsed itself to be a minor spelling mistake, lol. Nothing broken, but making a note to change the "primativeType" property in the VertexArray class to "primitiveType" next release probably isn't a bad idea.

**Comment by Jebbs** [comment]
That's embarrassing. :P
