### ISSUE TITLE
Noisy Output

### ISSUE THREAD

**Issue by kingsleyh** [Jebbs/DSFML#166]
Hi,

When my window runs it prints out a ton of stuff to the terminal that opened it - with stuff like:
Destroying Texture / Text etc 
Is there an off switch for this?

**Comment by aubade** [comment]
Yes! Compiling in release mode.

**Comment by Jebbs** [comment]
You can also compile in debug with the -version=DSFML_Quiet_Destructors

**Comment by Jebbs** [comment]
I'm going to leave this open though so that I don't forget to include this information in the new documentation/tutorials.

**Comment by Jebbs** [comment]
I think I might change this to not have the destructors be noisy on default.

**Comment by Jebbs** [comment]
The current 2.1 branch has no destructor output by default, but you can use version DSFML_Noisy_Destructors to turn it on if you like.

**Comment by dmi7ry** [comment]
Sorry for noob question, I tried googling but found nothing (my English is very bad and for me is hard read lot of texts). How I can use `DSFML_Noisy_Destructors` with dub?

**Comment by Jebbs** [comment]
Just add '-version=DSFML_Noisy_Destructors' to the dflags field in your dub.json or dub.sdl

**Comment by dmi7ry** [comment]
Thank you!
