### ISSUE TITLE
Can't get DSFML working on windows 8.1

### ISSUE THREAD

**Issue by kingsleyh** [Jebbs/DSFML#167]
Hi

When I download the win32 zip provided for DSFML and then create a test project called circles with this dub.json

{
	"name": "circles",
	"description": "A minimal D application.",
	"copyright": "Copyright © 2015, kings",
	"authors": ["kings"],
	"lflags" : ["+C:\\Users\\kings\\Downloads\\DSFML-Current-Win32\\DSFML-Current\\lib\\dmd\\"],
	"dependencies": {
		"dsfml:graphics": "~master"
	}
}

When I run dub - I get a pop up box saying that the program can't start because dsfml-graphics-2.dll is missing from your computer. Try reinstalling the program to fix this problem 

Am I missing something or does DSFML not work on windows 8.1?

**Comment by Jebbs** [comment]
All you need to do is place the right dll's in the same directory as the .exe file or have them in a directory that is in your PATH.

As for Linux, if they aren't in a standard path, running this command in the same directory as your executable will work:
'''export LD_LIBRARY_PATH=path/to/dsfml/shared/libs && ./dsfml-app'''

**Comment by kingsleyh** [comment]
Ok great thanks - I’ve got it working on a fresh install of Ubuntu now:   https://github.com/masterthought/dtanks/wiki/Installation-and-Running <https://github.com/masterthought/dtanks/wiki/Installation-and-Running>

I will try now on windows with your instructions

**Comment by kingsleyh** [comment]
Ok great thanks - copying the DLL’s into the root of my project worked fine. I’ve updated my instructions to include getting it running on Windows.

**Comment by kingsleyh** [comment]
Is it possible to automate that CMAKE step or does it have to be a manual process to create the libs?

**Comment by Jebbs** [comment]
At what step would you want it to be automated?

**Comment by kingsleyh** [comment]
Ideally all of it - so I could just run generate.bat / generate.sh and it would build me the DSFML binaries for my platform

**Comment by kingsleyh** [comment]
I say this because imagine at my event there will be say 20 people all with different operating systems and versions of stuff installed and they all need to be able to get up and running with dtanks - currently some of them will be fine with the prebuilt stuff but I bet a ton of them will need to build from source

**Comment by Jebbs** [comment]
It's actuall pretty simple.

'''git clone https://github.com/Jebbs/DSFML-C.git
cd DSFML-C
cmake .
make'''

will generate and execute the makefiles. If you're using vc++ on Windows use nmake instead of make. I guess I could make a script for it, but it's so simple I don't know if it's really needed.

**Comment by kingsleyh** [comment]
I thought there was more to it than that? I mean I want to automate this procedure:   https://github.com/Jebbs/DSFML/wiki/Building-DSFML-Libraries-From-Source(Linux) <https://github.com/Jebbs/DSFML/wiki/Building-DSFML-Libraries-From-Source(Linux)>

There are 2 different stages mentioned in the building from source wiki - first go and build a static lib for SFML and then go and build the static libs for DSFML. You are just automating the second part in that little script?

**Comment by Jebbs** [comment]
Nope, that's an old doc. The newest version of DSFML-C actually contains the sources for SFML. Now you only have to build one thing.

I've just been busy enough to where I haven't updated all the information yet.

**Comment by kingsleyh** [comment]
Wow it works :) that's much easier thanks
