### ISSUE TITLE
Image saveToFile string isn't converted to zero terminating

### ISSUE THREAD

**Issue by NCrashed** [Jebbs/DSFML#169]
https://github.com/Jebbs/DSFML/blob/master/src/dsfml/graphics/image.d#L329

```D

bool saveToFile(string fileName)
{
    import dsfml.system.string;
    bool toReturn = sfImage_saveToFile(sfPtr, fileName.ptr); // here
    err.write(toString(sfErr_getOutput()));
    return toReturn;
}
```

**Comment by Jebbs** [comment]
I think this is a duplicate, but I can't seem to find the first issue so I'll leave this open.

Thanks!

**Comment by luke5542** [comment]
Looks like https://github.com/Jebbs/DSFML/issues/162 is the previous issue.

**Comment by Jebbs** [comment]
Yep! That's the one!

I'll mark this as a duplicate and close. I'm also working on the library all weekend, so this'll get fixed probably today.
