### ISSUE TITLE
Window.view is not very useful with const restriction

### ISSUE THREAD

**Issue by aubade** [Jebbs/DSFML#172]
I'm trying to play around with fullscreen in my project for the first time, and adjusting the window's View seems to be the go-to way to do this. However, the view() getter property on the window returns a read-only object, and there's no .dup or copy constructor to get a modifiable version of the view for adjusting.

**Comment by Jebbs** [comment]
The returned view is const do to a different issue (we shouldn't be allowed to modify it directly). This smelly issue should be better once I change View to a struct.

But...there is [this](https://github.com/Jebbs/DSFML/blob/2.1-rc/src/dsfml/graphics/view.d#L155), though. Just so you know. :P

**Comment by aubade** [comment]
...I.. I swear I read the docs and file first. THis is what I get for coding while sleepy! Sorry about that.

**Comment by Jebbs** [comment]
Set to be fixed by #199
