### ISSUE TITLE
convert window to image?

### ISSUE THREAD

**Issue by Laeeth** [Jebbs/DSFML#173]
Hi.

I would like to be able to save a window to PNG format.  Not quite sure how the memory model works, and this may cause problems, but the following seems to work.

class RenderWindow : Window, RenderTarget
{
       auto capture()
    {
        return new Image(sfRenderWindow_capture(cast(const sfRenderWindow*) sfPtr));
    }
}

and then:
window.capture.saveToFile("./test.png");

ie there is missing the functionality in the RenderWindow class to convert a window to an Image, as far as I can see.

Laeeth.

**Comment by Jebbs** [comment]
I think what happened was I confused RenderWindow's capture method with Texture's updateFromWindow somehow. Occasionally CSFML had to do things like this to make things make sense for C, and I probably assumed this was like that.

**Comment by Jebbs** [comment]
Closing this issue since this functionality was added at some point. The `Texture.update()` method which takes in a `Window` or `RenderWindow` was also added since `RenderWindow.capture()` was deprecated.
