### ISSUE TITLE
Building with OSX 10.10.5

### ISSUE THREAD

**Issue by joelcnz** [Jebbs/DSFML#175]
I've installed SFML (install.sh). And DSFML looks installed. I'm using DUB, but I get this..

Joels-MacBook-Pro:dsfml-dubtest joelcnz$ dub build
WARNING: A deprecated branch based version specification is used for the dependency dsfml:graphics. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Target dsfml:system ~master is up to date. Use --force to rebuild.
Target dsfml:window ~master is up to date. Use --force to rebuild.
Target dsfml:graphics ~master is up to date. Use --force to rebuild.
Building dsfml-dubtest ~master configuration "application", build type debug.
Compiling using dmd...
Linking...
ld: warning: path '/Library/Frameworks/dsfml-graphics.framework/dsfml-graphics' following -L not a directory
ld: library not found for -ldsfml-graphics
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- errorlevel 1
FAIL .dub/build/application-debug-posix.osx-x86_64-dmd_2068-3324A1797AA39F9E98D6C080332C6DAE/ dsfml-dubtest executable
Error executing command build: dmd failed with exit code 1.

Thanks for any help.

**Comment by luke5542** [comment]
Could you provide your dub.json file? It looks like you don't have things setup correctly for linking the dsfml libraries.

In my setup, I have the compiled .dylib files in a libs/ directory on the same level as dub.json and source/ and in my dub.json I have the line:

```
"lflags-osx": ["-Llibs"]
```

under an OSX-specific project configuration.

**Comment by Jebbs** [comment]
I think the warning says it all.

/Library/Frameworks/dsfml-graphics.framework/dsfml-graphics is not a directory. Thus, it can't find the binaries to link with. A simple change to the path to the framework in your dub.json should fix it.

**Comment by joelcnz** [comment]
I don't have any .dylib files that I can see.

**Comment by luke5542** [comment]
To compile a DSFML program via DUB, you need the dependency entry, which it appears you have correctly setup, and you need the compiled shared libraries to link against. On OSX, these libraries come in the form of .dylib files, as available from the [README](http://jebbs.github.io/DSFML/bins/osx/DSFML-Current-OSX.zip). The linker needs to know where these files are so that it can properly reference them when running.

What have you done as setup so far? Have you tried the solution from @Jebbs?

**Comment by joelcnz** [comment]
I tried stuff with @Jebbs information, nothing worked.

I've copied .dylib files to lib on the same directory, but  I get  -- ld: warning: directory not found for option '-Llibs'

{
    "name": "dsfml-dubtest",
    "description": "A minimal D application.",
    "copyright": "Copyright © 2013, Jeremy",
    "authors": ["Jeremy"],
	"lflags-osx" : ["-Llibs"],
    "dependencies": 
    {
        "dsfml:graphics": "~master"
    }
}

**Comment by luke5542** [comment]
Hmm... this error sounds like a naming conflict, where it's expecting "libs" but there only exists "lib". Other than that it looks like it should be working.

**Comment by joelcnz** [comment]
Yay, it works! (and the program is happy too!).

Thanks @Jebbs and luke5542!

**Comment by luke5542** [comment]
Glad to hear it!

**Comment by joelcnz** [comment]
Ok, now I'm trying out more stuff.

using these imports:
import dsfml.system;
import dsfml.window;
import dsfml.graphics;
import dsfml.audio;

I get this:
Joels-MacBook-Pro:Puffer joelcnz$ dub
WARNING: A deprecated branch based version specification is used for the dependency dsfml:graphics. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Target dsfml:system ~master is up to date. Use --force to rebuild.
Target dsfml:window ~master is up to date. Use --force to rebuild.
Target dsfml:graphics ~master is up to date. Use --force to rebuild.
Building puffer ~master configuration "application", build type debug.
Compiling using dmd...
Linking...
Undefined symbols for architecture x86_64:
  "_D5dsfml5audio11soundbuffer11SoundBuffer7__ClassZ", referenced from:
      _D49TypeInfo_xC5dsfml5audio11soundbuffer11SoundBuffer6__initZ in puffer.o
  "_D5dsfml5audio12__ModuleInfoZ", referenced from:
      _D7example12__ModuleInfoZ in puffer.o
  "_D5dsfml5audio5music5Music6__ctorMFZC5dsfml5audio5music5Music", referenced from:
      __Dmain in puffer.o
  "_D5dsfml5audio5music5Music7__ClassZ", referenced from:
      __Dmain in puffer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- errorlevel 1
FAIL .dub/build/application-debug-posix.osx-x86_64-dmd_2068-AE7B31F77434B84DFC8740D29DC1295F/ puffer executable
Error executing command run: dmd failed with exit code 1.

Joels-MacBook-Pro:Puffer joelcnz$

**Comment by luke5542** [comment]
I'm afraid I cannot help with this particular problem.

Any ideas @Jebbs?

**Comment by Jebbs** [comment]
The master branch is actually out of date. (Probably should have started with that)

Try the 2.1rc branch and this  backend: https://github.com/Jebbs/DSFMLC

 It's not quite done, but mostly there. Also, pretty much all of the most recent work has been on os x  you should be in good shape.

**Comment by Jebbs** [comment]
It's been a while since this was opened, and everything should be fixed now. 

The 2.1 tag exists, and it should be used with dub, but master is essentially at 2.1 so it can be used as well. Any issues with this still?
