### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by joelcnz** [Jebbs/DSFML#176]
This doesn't work:
	if (Keyboard.isKeyPressed(Key.A)) {
		
	}

What do I put?

**Comment by Jebbs** [comment]
if(Keyboard.isKeyPressed(Keyboard.Key.A)
{
}

By the way, for things like this you can always ask questions on the DSFML forums instead of opening an issue.

http://en.sfml-dev.org/forums/index.php?board=13.0

**Comment by joelcnz** [comment]
Ok. Thanks, I'll do that.
