### ISSUE TITLE
Rearranging Enums to make their usage closer to SFML

### ISSUE THREAD

**Issue by luke5542** [Jebbs/DSFML#178]
For example, when referencing specific Keys in Keyboard, DSMFL requires:

``` D
Keyboard.Key.A
```

while SFML requires:

``` C++
sf::Keyboard::A
```

This isn't a problem for DSFML, but I'm just wondering if there's any significant issue with reducing verbosity and going the SFML route. Example code for this idea would be the [Enum values without enum namespace](http://p0nce.github.io/d-idioms/#Porting-from-C-gotchas) idiom.

I think the current implementation might give more compile-time safety, but I'm not entirely certain about that. Either way, this is just an idea I thought would be worth discussing.

**Comment by Jebbs** [comment]
I have thought about this, but was never sure on how to proceed. Yes, we could use an anonymous enum of an aliased type and have the syntax closer to SFML's, but do we want to?

Translation would be easier and people coming from C++/SFML wouldn't get caught with it, but I think there is something to be said about the way D does its enum's. More to type, but I think it increases readability and what not. You know that we're dealing with keyboard keys without having to even think about it. It's been a while, but I'm pretty sure that C# also does enums the same way as D, 
which is maybe why I don't mind it (I came to D from C#).

I'm not against changing it nor really against keeping it the way it is. This is definitely something that should be decided after much input, but I do want to point out that while I try to match SFML's way of doing things as much as I can, we should try to use idiomatic D even more so. That is going to be my focus after this upcoming release.

**Comment by aubade** [comment]
I'm going to tentatively vote for a namespaced enum (Maybe just Key instead of Keyboard.Key, but that's not a dealbreaker)

**Comment by luke5542** [comment]
@Jebbs Your last point rings most strongly with me. I agree that it's best to make it as close to standard D style as possible.

So far I see the following adv/dis for anonymous enums:
+ Similar usage to SFML
+ Less verbose

And for the current named enums we get:
+ Idiomatic D
+ Compile-time type safety
+ More explicit usage

I think my original question has been answered now. And now that @aubade mentions is, I'm leaning in that direction as well.

**Comment by Jebbs** [comment]
Closing this as I'm going to keep things as is with enums.

(unless someone has a better argument and wants to reopen)
