### ISSUE TITLE
Enable Multi-OS testing support (Travis CI)

### ISSUE THREAD

**Issue by Jebbs** [Jebbs/DSFML#185]
While it is beta, Travis CI currently supports building for OS X. I should set this up, assuming that a d compiler can be installed via homebrew (which I assume it can).

**Comment by luke5542** [comment]
This sounds like an excellent step! Even better if it's possible to publish the builds that Travis makes (which I have no idea about). I can also confirm that dmd, and I think at least one of LDC/GDC, can be installed through brew.

**Comment by Jebbs** [comment]
Emailed the support team to get OS X enabled for both DSFML and DSFMLC. I'll play around with this for a bit, but it should hopefully be up and running in a couple of days.

**Comment by Jebbs** [comment]
I also stumbled across appveyor which supports CI for windows. I'll get that all going as well.

**Comment by Jebbs** [comment]
Looks like Travis enabled OS X globally. We're good to go for doing CI on all OS's
