### ISSUE TITLE
SFML version jump

### ISSUE THREAD

**Issue by Jebbs** [Jebbs/DSFML#197]
Since I've fallen behind I'm going to do a huge jump to catch up. 

The last release was version 2.3.2, however version 2.4 is in the works.

Should I shoot for the last released version or just work on the next release?

**Comment by aubade** [comment]
I'd personally vote to target stable versions; they're a slower-moving target--tracking the in-development version could potentially get very messy (e.g. with things like the BlendMode API change) and would put more pressure on you or us to keep up. Being a point-release or two behind current is better, IMO, than being reliant on a particular out-of-date git snapshot or commit.

**Comment by Jebbs** [comment]
Yep, I think you're right. Having to deal with potential changes could be tricky, and that is a non issue in a released version. I really hope to (someday) get to a point where the DSFML master is at the same point as SFML's master though.

A man can dream....

**Comment by Jebbs** [comment]
Closing this as I fell more behind and I'm close on a 2.4 release.
