### ISSUE TITLE
Dmd generated executable segfaults

### ISSUE THREAD

**Issue by erdemoncel** [Jebbs/DSFML#212]
I've built DSFML and DSFMLC from source code. When I try to compile first dsfml program it compiles fine. But when I try to run executable I get segmentation fault error.

I've attached the strace output. 

strace -f dmd -run deneme.d (My program name is deneme means test)

Any ideas. Thanks..
[hata.txt](https://github.com/Jebbs/DSFML/files/116461/hata.txt)

**Comment by Jebbs** [comment]
Do you know where it is failing?

I don't have any experience reading strace output, but the only error I can see in that file is at the end of it, and it looks like a complation failure. 

Try removing the -run switch and see if you get a compiler error.

**Comment by aubade** [comment]
I don't think the strace output will be too useful; it only logs system-calls. Can you put the code you're testing online, and give us a gdb backtrace?

**Comment by erdemoncel** [comment]
Here is the source code:

```
module main;

import dsfml.graphics;

void main(string[] args)
{
    auto window = new RenderWindow(VideoMode(800,600),"Hello DSFML!");

    auto head = new CircleShape(100);
    head.fillColor = Color.Green;
    head.position = Vector2f(300,100);

    auto leftEye = new CircleShape(10);
    leftEye.fillColor = Color.Blue;
    leftEye.position = Vector2f(350,150);

    auto rightEye = new CircleShape(10);
    rightEye.fillColor = Color.Blue;
    rightEye.position = Vector2f(430,150);

    auto smile = new CircleShape(30);
    smile.fillColor = Color.Red;
    smile.position = Vector2f(368,200);

    auto smileCover = new RectangleShape(Vector2f(60,30));
    smileCover.fillColor = Color.Green;
    smileCover.position = Vector2f(368,200);

    while (window.isOpen())
    {
        Event event;

        while(window.pollEvent(event))
        {
            if(event.type == event.EventType.Closed)
            {
                window.close();
            }
        }

        window.clear();

        window.draw(head);
        window.draw(leftEye);
        window.draw(rightEye);
        window.draw(smile);
        window.draw(smileCover);

        window.display();
    }
}
```
I compiled program like this : 

$ dmd -g -debug -ofdeneme deneme.d -IDSFML/src -L-LDSFMLC/lib -L-LDSFML/lib -L-ldsfml-graphics -L-ldsfml-window -L-ldsfml-system -L-ldsfmlc-graphics -L-ldsfmlc-window -L-ldsfmlc-system

Also I think there is a minor typo in tutorial on compiling a dsfml program on Linux and OSX. I think -IDSFML/scr should be -IDSFML/src

>  Can you put the code you're testing online, and give us a gdb backtrace? 

Here is the gdb backtrace.

[gdb.txt](https://github.com/Jebbs/DSFML/files/117279/gdb.txt)

Thanks..

**Comment by erdemoncel** [comment]
> Do you know where it is failing?

The program doesn't even starts.

> Try removing the -run switch and see if you get a compiler error.

Here is the strace -f dmd deneme.d output.

[strace.txt](https://github.com/Jebbs/DSFML/files/117291/strace.txt)

**Comment by aubade** [comment]
Hrm; well it's crashing during the RenderStates static this() {}. It'll be a bit before I can try this on Linux and see if I have the problem too, but my instinct is this might not be a good idea; it's forcing the creation of a GL context as soon as a thread begins regardless of whether it's used or what settings that context might require. 

@erdemoncel What video card do you have, out of curiosity? And if it's AMD or Nvidia, are you using the proprietary driver?

@Jebbs, would it be possible to make on-demand static getters for these? something like

```
@property auto emptyTexture () {
     static Texture tex;
     if (tex is null) tex = new Texture();
     return tex;
}
```

**Comment by erdemoncel** [comment]
@ aubade I have Intel GMA 3650 graphics card. When I report this bug proprietary driver was not installed. I then installed cedarview drivers but I the program still segfaults.

**Comment by aubade** [comment]
Okay, I'm not able to reproduce the issue on my system, but could you try applying this patch: https://dl.dropboxusercontent.com/u/187059/dsfml-renderstates.diff

to your local copy of DSFML? (If you're using dub, it will be in ~/.dub/packages/dsfml-<version> )

If you're not familiar with the procedure, you can just run this command from the DSFML directory:
```
$ patch -p0 < /path/to/dsfml-renderstates.diff
```

and see if that fixes your issue?

**Comment by erdemoncel** [comment]
I applied the patch but this time I suppose it crashes during the RenderWindow class constructor. Here is the gdb backtrace.

[gdb.txt](https://github.com/Jebbs/DSFML/files/117576/gdb.txt)

**Comment by Jebbs** [comment]
It looks like you're having a problem even making a GL Context. Do you have this issue with anything else that needs a context, such as other games?

**Comment by aubade** [comment]
Yeah, my next suggestion would be, if other GL stuff does work, try compiling some of the C++ SFML demos and seeing if those run.

**Comment by erdemoncel** [comment]
I shouldn't be able to compile C++ SFML examples. So this might be a hardware issue as you mention.
Thanks.
