### ISSUE TITLE
Google Summer of Code proposal

### ISSUE THREAD

**Issue by Jebbs** [Jebbs/DSFML#216]
Hey all,

I'm currently working on a proposal for DSFML for this year's GSoC. I have many ideas/tasks in my list already, such as improving tutorials, including examples and example projects, improving testing, improving documentation, improving build tools, updating the internal SFML version, improving the speed of future updating, adding iOS and Android support for ldc, and also general bug fixes.

What kind of things are on your mind that you would like to see added/improved/changed in DSFML? I'm currently open to any ideas anyone might have. I'll probably tighten up the list before the proposal is submitted so I don't try to take on too much, but for now just throw everything that you got at me!

I'll also post my proposal here and on the D forums to get feedback, so be on the lookout for that!

**Comment by aubade** [comment]
My biggie is the new SFML version; i'm interested in the BlendMode changes, joystick identification, and OpenGL/ES support.

My only other thoughts diverge from upstream SFML a fair bit; for example one-channel 8-bit texture upload support (To use with a pixel shader for emulating palettized graphics), or Geometry shaders.

**Comment by Jebbs** [comment]
It is unlikely that I will add any functionality that isn't in SFML proper, but you could always make feature requests to the SFML team!

**Comment by Jebbs** [comment]
[DSFML Summer of Code Proposal - First Draft.pdf](https://github.com/Jebbs/DSFML/files/160651/DSFML.Summer.of.Code.Proposal.-.First.Draft.pdf)


I've been working on this a bit for the past few days, and it is much better in terms of everything it covers. Still needs some work, especially with culling down repeated information, and just general wording and possibly relaying how excited I am for something like this, but good enough for feedback.

**Comment by Jebbs** [comment]
There wasn't much feedback on my proposal on the D forums. I think that people might not be that interested in it as a project. I might need to either change something in the proposal or pick a different topic for GSoC.

**Comment by nikibobi** [comment]
Sounds great! I might be up for taking the project for GSoC

**Comment by Jebbs** [comment]
It's not that I don't want to do it, I just don't know how likely it is to be accepted.

I was planning on sending it today to the mentor team for their feedback, but I also started another proposal in the mean time.

**Comment by Jebbs** [comment]
I managed to get in contact with Craig Dillabough who looked over my proposal. It's a bit of a downer, but based on what he said I'm not confident this would get picked up..

The other proposal I'm working on is looking good though. Depending on how much time I have to spend on it I might have time to work on DSFML as well. Maybe I can do 1 full day of DSFML work a week.

**Comment by Jebbs** [comment]
@nikibobi,

If you think you could work some magic and can get the proposal accepted, go for it. One issue Craig brought up was the lack of mentors for game development stuff. There are currently none. I might be up for taking that role if I'm able to do that and be a student participant at the same time.

Let me know what you think.

**Comment by Jebbs** [comment]
DSFML will get worked on this summer, but won't be a part of GSoC.

Sad :(
