### ISSUE TITLE
dmd-2.071.0 error in soundbuffer.d

### ISSUE THREAD

**Issue by dmi7ry** [Jebbs/DSFML#219]
With dmd-2.071.0 I have some errors:

    C:\Users\...\src\dsfml\audio\soundbuffer.d(63,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(148,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(172,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(196,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(222,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(247,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundrecorder.d(61,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundrecorder.d(92,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundstream.d(82,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundstream.d(278,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    dmd failed with exit code 1.

dmd-2.070.2 works fine

**Comment by Jebbs** [comment]
Looks like this has to do with the updated import rules. I guess the function is checked without looking at imports first, which sees Object.toString() instead of dsfml.system.string.toString() which was imported.

Easy to fix. Should be out tonight.

**Comment by Jebbs** [comment]
I'm not sure if this meets what you need, but @aubade just did a bunch of work towards DSFML 2.3, which contains a fix for this that got merged into the 2.3 branch today. 

If you would rather I fix the master branch, then I can do that for you too.

**Comment by joelcnz** [comment]
I get more errors (2.1):

Joels-MacBook-Pro:DSFML joelcnz$ dub
Performing "debug" build using dmd for x86_64.
dsfml 2.1.0: building configuration "library"...
src/dsfml/graphics/text.d(69,3): Deprecation: dsfml.graphics.renderstates.Rebindable is not visible from module text
src/dsfml/graphics/text.d(78,3): Deprecation: dsfml.graphics.renderstates.Rebindable is not visible from module text
src/dsfml/graphics/sprite.d(59,3): Deprecation: dsfml.graphics.renderstates.Rebindable is not visible from module sprite
src/dsfml/audio/soundbuffer.d(64,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundbuffer.d(150,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundbuffer.d(174,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundbuffer.d(198,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundbuffer.d(224,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundbuffer.d(249,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundrecorder.d(61,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundrecorder.d(92,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundstream.d(82,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/audio/soundstream.d(278,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/font.d(86,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/font.d(109,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/font.d(135,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/image.d(115,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/image.d(138,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/image.d(161,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/image.d(300,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/rendertexture.d(96,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/rendertexture.d(388,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
src/dsfml/graphics/renderwindow.d(244,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
dmd failed with exit code 1.

**Comment by Jebbs** [comment]
Yeah, I'm a little behind with updating to newer compilers. I should have that fixed this evening and I will have these errors handled as soon as I can.

**Comment by Jebbs** [comment]
As a work around, there are compiler flags to have it build using the old import rules so you could do that for the time being.

**Comment by joelcnz** [comment]
I can't seem to find the switch to build it with the old import rules. Can you tell me?

**Comment by Jebbs** [comment]
Sure thing:

`-transition=import`

Let me know if that doesn't work and I'll get things fixed for you.

**Comment by joelcnz** [comment]
Tried the in dub.json file: "DFLAGS": ["transition=import"],

But no different.

**Comment by Jebbs** [comment]
I think you still need the `-` in front of it.

**Comment by joelcnz** [comment]
I can't get it to go any-which-way. I've tried --force. And '-transition=import,10378'

**Comment by sigod** [comment]
Try `"dflags-dmd": [-transition=import]`.

**Comment by joelcnz** [comment]
That didn't work either. :-/

**Comment by joelcnz** [comment]
I did use quotes (["-transition=import"]).

**Comment by sigod** [comment]
> I did use quotes (["-transition=import"]).

Sorry, I somehow forgot quotes. Do you use DMD?

**Comment by joelcnz** [comment]
Yes, I use DMD on OSX.

**Comment by joelcnz** [comment]
I still can't get it to work.

**Comment by dmi7ry** [comment]
I also tried add `-transition=import` to dub, also without result. (dmd, windows)

**Comment by Jebbs** [comment]
Weird.

I'll be able to get to this tomorrow. For now, just use the last compiler?

**Comment by Jebbs** [comment]
Sorry about the wait. I got called in to work when I didn't expect it.

I'm currently waiting for appveyor to finish building to confirm we're good to go on all systems. After that I'll merge things into master. If you use DUB then you shouldn't have to change anything. If you don't then you'll have to rebuild DSFML yourself.
