### ISSUE TITLE
Setting shader parameters always allocates

### ISSUE THREAD

**Issue by aubade** [Jebbs/DSFML#225]
This isn't exactly a critical issue, but it's worth noting that due to the way string conversion works, there's not currently a @nogc way of setting parameters on a Shader, even when working with a compile-time literal. 

It might be worth looking into a way of doing this (possibly by providing const(char)* overloads and letting the user handle any needed conversion on their end.)

**Comment by Jebbs** [comment]
This is a problem in everything that uses toStringz.

I'm currently considering doing away with that function and instead passing the address of the string and its length and create an std::string in the c++ end to avoid these tiny gc allocations.

**Comment by aubade** [comment]
That actually sounds like a really good idea. I could take a look at doing this on the 2.3 branch if you're busy elsewhere.

**Comment by Jebbs** [comment]
Yeah, go for it. I'm super busy with my GSoC project. I won't be able to do more DSFML stuff until after I quit my regular job when GSoC officially starts.

**Comment by Jebbs** [comment]
Closed by #226
