### ISSUE TITLE
error while loading shared libraries: libdsfmlc-graphics.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nandryshak** [Jebbs/DSFML#233]
On Arch Linux 64-bit.

I installed DSFMLC as per the instructions on: http://dsfml.com/docs/buildingfromsource.html

`libdsfmlc` builds and gets installed in `/usr/local/lib` as expected.

I ran `dub init test`, and added a dependency to `dsfml` like this:

```
"dependencies": {
    "dsfml:graphics": "~>2.1"
}
```

Running `dub run --force` at this point results in the following error:

```
$ dub run --force
Performing "debug" build using dmd for x86_64.
dsfml:system 2.1.1: building configuration "library"...
dsfml:window 2.1.1: building configuration "library"...
dsfml:graphics 2.1.1: building configuration "library"...
test ~master: building configuration "application"...
Linking...
Running ./test 
./test: error while loading shared libraries: libdsfmlc-graphics.so.2: cannot open shared object file: No such file or directory
Program exited with code 127
```

Any ideas?

**Comment by Jebbs** [comment]
I'm not sure if Arch is one of them, but in some distros `/usr/local/lib` might not be included in your runtime search path. You can either add `/usr/local/lib` to the `LD_LIBRARY_PATH` environmental variable, add a config file to the `/etc/ld.so.conf.d` directory, or pass `-rpath=/usr/local/lib` to the linker.

Hopefully that helps!

**Comment by nandryshak** [comment]
That does help! It works now, thanks.
