### ISSUE TITLE
Home Brew support macOS

### ISSUE THREAD

**Issue by joelcnz** [Jebbs/DSFML#236]
Would Home Brew be able be supported? It seems to only have 2.4.0 version of SFML, though I'm not sure how to use brew for getting different versions.

**Comment by Jebbs** [comment]
It would probably be a good thing. I'll look into it and will try to get it set up for the next release.

**Comment by joelcnz** [comment]
Thanks Jebbs. I look forward to it.

**Comment by joelcnz** [comment]
Its been a while. Are you still working on it?

**Comment by Jebbs** [comment]
Honestly, I haven't been able to even start. School is keeping me pretty busy. If you have any extra time, would you start looking into this for me? If I have all the information I can get it done faster.

**Comment by joelcnz** [comment]
Thanks for the reply. I haven't been able to program much lately. I'll
wait, I guess.

**Comment by Jebbs** [comment]
It's been a long time since I did any testing on a mac, but the error you're getting is a dub dependency error. What does dub give you when you use the verbose flag?

**Comment by joelcnz** [comment]
Joels-MacBook-Pro:LetsPush joelchristensen$ dub --verbose upgrade
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /Users/joelchristensen/.dub/packages/local-packages.json
Ignoring version specification (~master) for path based dependency ../../
Ignoring version specification (~master) for path based dependency ../../
Ignoring version specification (~master) for path based dependency ../../
Note: Failed to determine version of package pusher at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /Users/joelchristensen/.dub/packages/local-packages.json
Ignoring version specification (~master) for path based dependency ../../
Ignoring version specification (~master) for path based dependency ../../
Ignoring version specification (~master) for path based dependency ../../
  Found dependency dsfml:audio 2.1.1
    Found dependency dsfml:system 2.1.1
  Found dependency dsfml:graphics 2.1.1
    Found dependency dsfml:window 2.1.1
Upgrading project in /Users/joelchristensen/jpro/dpro2/Praise/LetsPush
Search for versions of dsfml (1 package suppliers)
Return for dsfml: [2.1.1, 2.1.0, ~master, ~2.3, ~2.0]
Root package pusher reference dsfml:audio ~>2.4 cannot be satisfied.
Joels-MacBook-Pro:LetsPush joelchristensen$

**Comment by Jebbs** [comment]
That looks like a problem with the `package.json` file referencing a tag that doesn't exist yet. I don't have many issues left for the 2.4 release that require work on the binding itself, so ther'll be a release candidate tag soon which should fix this (and I can prevent it in the future).

**Comment by joelcnz** [comment]
Thanks for all your work, Jebbs.
