### ISSUE TITLE
Ready to use package?

### ISSUE THREAD

**Issue by RUSshy** [Jebbs/DSFML#246]
Hello

Is it possible to release a ready to use package with all dlls requiered to build a simple Window

Because atm this is confusing this seems to use an outdated version of SFML, and 2.3 and 2.4 branch refuse to build

I think it is necessary to release ready to use package for simplicity

EDIT: I'm on Windows

**Comment by Jebbs** [comment]
>Because atm this is confusing this seems to use an outdated version of SFML, and 2.3 and 2.4 branch refuse to build

That's because those aren't officially released versions, they're still in progress. I'm working on the 2.4 branch, but it still has some work to be done until it's ready. I'm going to try to have it released before the end of march, though.

The 2.1 version should work, even if it is outdated. What problems are you having with it?

**Comment by RUSshy** [comment]
Thanks!

The problem is have with 2.1 is it doesn't work, i thought it was because it was outdated

```
Fetching dsfml 2.1.1 (getting selected version)...
Performing "debug" build using dmd for x86.
dsfml:system 2.1.1: building configuration "library"...
dsfml:audio 2.1.1: building configuration "library"...
dsfml:window 2.1.1: building configuration "library"...
dsfml:graphics 2.1.1: building configuration "library"...
dsfml:network 2.1.1: building configuration "library"...
dsfml 2.1.1: building configuration "library"...
the-roguer ~master: building configuration "application"...
Linking...
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
dsfmlc-audio.lib
 Error 43: Not a Valid Library File
Error: linker exited with status 1
dmd failed with exit code 1.
```

**Comment by Jebbs** [comment]
Did you use implib to make import libraries? That looks like your problem to me.

**Comment by RUSshy** [comment]
I'm not using implib, maybe my download was corrupted i'll try again to redownload everything

**Comment by RUSshy** [comment]
oh my bad i was using x64 libs, building with `` dub --arch=x86_64`` works :)
