### ISSUE TITLE
Consider adding overloads for all three kinds of strings

### ISSUE THREAD

**Issue by Jebbs** [Jebbs/DSFML#95]
People use different kinds of strings for different reasons, and I would hate for them to have to worry about that when using the library. I think I'd like to provide overloads for all functions and methods that use strings and do any needed casting internally.

**Comment by Jebbs** [comment]
Here's what I ended up with instead of doing actual overloads. 

For Window and RenderWindow:

```
this(T)(VideoMode mode, immutable(T)[] title, Style style = Style.DefaultStyle, ref const(ContextSettings) settings = ContextSettings.Default)
		if (is(T == dchar)||is(T == wchar)||is(T == char))

void create(T)(VideoMode mode, immutable(T)[] title, Style style = Style.DefaultStyle, ref const(ContextSettings) settings = ContextSettings.Default)
		if (is(T == dchar)||is(T == wchar)||is(T == char))

void setTitle(T)(immutable(T)[] newTitle)
		if (is(T == dchar)||is(T == wchar)||is(T == char))
```

And for Text:
```
this(T)(immutable(T)[] text, const(Font) font, uint characterSize = 30)
		if (is(T == dchar)||is(T == wchar)||is(T == char))

void setString(T)(immutable(T)[] text)
		if (is(T == dchar)||is(T == wchar)||is(T == char))

immutable(T)[] getString(T)() const
		if (is(T == dchar)||is(T == wchar)||is(T == char))
```

And then I am just converting everything to utf32 internally before passing it to SFML.

**Comment by aubade** [comment]
Would the std.traits.isSomeString!T template possibly help make things less verbose here? It might make things a little less verbose.

**Comment by Jebbs** [comment]
That's a good suggestion.

I'm trying to avoid unnecessary dependencies  to the standard library, so I'll probably just implement a little template myself since I already have a string module.

**Comment by SyntaxColoring** [comment]
@Jebbs What's the rationale behind avoiding dependencies to the standard library?

**Comment by Jebbs** [comment]
Unnecessary bloat mostly. Phobos is getting better, but it is hard to tell if modules are going to import a bunch of other modules. 

Another reason is unnecessary allocations. If I don't use Phobos then I can reduce the amount of pressure is on the GC and any collections that interrupt the application are more likely due to the user of the library.

On the other hand, maybe I'm just silly and I am needlessly avoiding it. Who knows? Maybe it warrants a discussion.
